// let number = (2)
// let value= (3)
// var result = number+value

// document.write("sum of 2 + 3 is " + result )
// document.write( value-number) 
// document.write(number*value
    
// )
// document.write(value/number)
// document.write(value%number)
// let valuee;
// document.write(valuee)
// valuee= (15)
// document.write("initial value " + valuee)
// valuee= (20)
// document.write("value after increment is"+ valuee)
// valuee=(valuee+7)
// document.write("value after addition is" + valuee)
// valuee=(14)
// document.write("value after decrement is" + valuee)
// valuee=(valuee%7)
// document.write(valuee)
// let ticketPrice = (600)
// ticketPrice=(ticketPrice*5)
// document.write("cost of buying 5 tickets is " + ticketPrice)
// let table;
// let price1 = (300);
// let price2 = (350);
// let order1 = (40)
// let order2 = (50)
// let shipping = (150)
// document.write("price of 1 item  and quatity is " + price1 +   order1 + "price of 2 item and quantity is "  +price2   + order2 ) 
//   document.write("total cost is " +price1  +  price2  +shipping  )
// let studentsObtained = (450)
// let totalMarks = (500)
// document.write("total marks " + totalMarks  +"\n")  
// document.write("marks obtained " + studentsObtained + "\n" )
// document.write ("90%" )
// let usDollar = (104.8*10)
// let Saudia = (28)
// document.write(usDollar+ Saudia)
// let numbers =(2)
// document.write(numbers+ 5 *10)
// let result = (52)
// document.write(result/2)
// let currentYear = (2025)
// let birthYear = (1994)
// let yourAge = (currentYear-birthYear)
// document.write(yourAge)
// let radius = (2)
// const pi =(3.142)
// let result = (2*3.142*2)
// document.write(result)
// let chips= ("kurkuray")
// let age = (30)
// let maxAge =(70)
// let amountSnacks= (2)
// let result =(maxAge-age)
// document.write(result*amountSnacks)
